### PR TITLE
New implementation of FEM to DGM coupling

### PR DESCRIPTION
**Pull request by Matael**
Implementation of FEM to DGM coupling without deriving the "FEM-side" characteristics.

### CODE REVIEW

**Comment by Matael** [comment]
Given the observed convergence rates, this requires more investigation.

**Comment by OlivierDAZEL** [comment]
Les PR ont disparu ?

**Comment by OlivierDAZEL** [comment]
ok vu après mail précédent

On voit demain

**Comment by Matael** [comment]
Now the convergence issues has been identified as "error calculation errors", let's merge.

**Pull request merged**
